Repository Dev-Duke-Seo/rolling_team1, pull requests merged in 2024-01, with the labels that each got.

#8 [Design] 컴포넌트배치
  .gitignore
  pindex.html
  src/components/createpaper/Backgroundtext.jsx
  src/components/createpaper/Choosebackground.jsx
  src/components/createpaper/Choosetype.jsx
  src/components/createpaper/Createbutton.jsx
  src/components/createpaper/Createpaper.jsx
  src/components/createpaper/Formcontainer.jsx
  src/components/createpaper/Header.jsx
  src/components/createpaper/Toinput.jsx
Labels: question

#11 [Design & Func] 롤링페이퍼 메세지 보내기 레이아웃 및 From값 에러 상태 구현
  .gitignore
  package-lock.json
  src/components/Heading.jsx
  src/components/InputFrom.jsx
  src/pages/SendMessage.jsx
  src/pages/SendMessageForm.jsx
  src/router/router.jsx
Labels: 매운맛🔥, 디자인, 기능

#13 [Feature] 캐러셀을 위한 버튼 기능 추가
  src/components/Paper/Paper.jsx
  src/components/Paper/Paper.style.js
  src/components/Paper/PaperBox.style.js
  src/components/Paper/PaperContainer.jsx
  src/components/Paper/PaperContainer.style.js
  src/components/PaperInfo.jsx
  src/components/PaperInfo.style.js
  src/pages/List/List.style.js
Labels: 매운맛🔥, 기능

#20 [Func] 롤링페이퍼 메시지 보내기 페이지 : 생성하기 버튼 구현
  src/components/Button/SubmitButton.jsx
  src/pages/Message/SendMessage.jsx
  src/pages/SendMessage.jsx
Labels: 매운맛🔥, 기능

#19 [Design] list 페이지에 미디어 쿼리 적용
  src/GlobalStyles.jsx
  src/assetes/arrow-left.svg
  src/assetes/arrow-right.svg
  src/components/Layout.jsx
  src/components/Paper/Paper.style.js
  src/components/Paper/PaperBox.style.js
  src/components/Paper/PaperContainer.jsx
  src/components/Paper/PaperContainer.style.js
  src/components/PaperInfo.style.js
  src/pages/List/List.jsx
  src/pages/List/List.style.js
Labels: 매운맛🔥, 디자인

#27 [Func & Design] 롤링페이퍼 메세지 보내기 페이지: 에디터 기능 구현 및 페이지 레이아웃 변경
  package-lock.json
  package.json
  src/components/Button/SubmitButton.jsx
  src/components/Button/SubmitButton.style.jsx
  src/components/Button/ToggleButton.jsx
  src/components/Button/ToggleButton.style.jsx
  src/components/Input/InputText.jsx
  src/components/Input/InputText.style.jsx
  src/components/Text/Editor.jsx
  src/components/Text/Editor.style.jsx
  src/components/Text/Heading.jsx
  src/components/Text/Heading.style.jsx
  src/pages/Message/SendMessage.jsx
  src/pages/Message/SendMessageForm.jsx
  src/pages/Message/SendMessageForm.style.jsx
Labels: 매운맛🔥, 디자인, 기능

#31 [ Feat] post페이지 카드 조건부 렌더링 및 컴포넌트 추가 구현
  .gitignore
  src/apis/postApis.js
  src/assetes/delete-icon.svg
  src/assetes/plus-icon.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.style.js
  src/components/Card/CardContainer.jsx
  src/components/Card/CardContainer.style.js
  src/components/Card/PaperHeader.style.js
  src/components/Card/RelationBadge.jsx
  src/components/Card/RelationBadge.style.js
  src/components/Header/Header.jsx
  src/components/Header/Logo.jsx
  src/constants/ColorMapper.js
  src/pages/Post/Post.jsx
  src/pages/Post/Post.stytle.js
Labels: 기능

#30 [Design] 롤링페이퍼 메세지 보내기 페이지: 프로필 이미지 레이아웃 구현
  src/assetes/images/default-profile-img.png
  src/components/Button/ToggleButton.jsx
  src/components/ProfileImg/ProfileImgList.jsx
  src/components/ProfileImg/ProfileImgList.style.jsx
  src/components/ProfileImg/ProfileImgMain.jsx
  src/components/ProfileImg/ProfileImgMain.style.jsx
  src/pages/Message/SendMessage.jsx
  src/pages/Message/SendMessageForm.style.jsx
Labels: 매운맛🔥, 디자인

#36 [Design] 4색버튼 구현&스타일드 정리
  src/assetes/images/basket.jpg
  src/assetes/images/checkbgimg.svg
  src/assetes/images/desert.jpg
  src/assetes/images/mokoko.png
  src/assetes/images/sky.jpg
  src/components/CreatePaper/BackgroundBox.jsx
  src/components/CreatePaper/BackgroundSelector.jsx
  src/components/CreatePaper/BackgroundText.jsx
  src/components/CreatePaper/ColorImgSelector.jsx
  src/components/CreatePaper/CreateButton.jsx
  src/components/CreatePaper/CreatePaper.jsx
  src/components/CreatePaper/FormContainer.jsx
  src/components/CreatePaper/RecipientInput.jsx
Labels: 디자인, 기능

#33 [Func] 롤링페이퍼 메세지 보내기 페이지 : 프로필 이미지 불러오기
  src/apis/profileApis.js
  src/components/ProfileImg/ProfileImgList.jsx
  src/components/ProfileImg/ProfileImgMain.jsx
  src/components/ProfileImg/ProfileImgMain.style.jsx
  src/components/ProfileImg/ProfileImgOption.jsx
  src/components/ProfileImg/ProfileImgOption.style.jsx
  src/pages/Message/SendMessage.jsx
Labels: 매운맛🔥, 기능

#44 [Func] 롤링페이퍼 메세지 보내기 페이지 : 함수 호출 기능 구현 및 이벤트 적용
  package-lock.json
  src/assetes/images/default-profile-image.png
  src/components/Button/SubmitButton.style.jsx
  src/components/Button/ToggleButton.jsx
  src/components/Input/InputText.jsx
  src/components/ProfileImages/ProfileImagesMain.jsx
  src/components/ProfileImages/ProfileImagesMain.style.jsx
  src/components/ProfileImages/ProfileImagesOptionList.jsx
  src/components/ProfileImages/ProfileImagesOptionList.style.jsx
  src/components/ProfileImg/ProfileImgMain.jsx
  src/components/ProfileImg/ProfileImgOption.jsx
  src/components/Text/Editor.jsx
  src/pages/Message/SendMessage.jsx
Labels: 매운맛🔥, 기능

#47 [Feat] 페이지 간 이동 및 id 파라미터 전달 + 리팩토링
  src/GlobalStyles.jsx
  src/apis/getApi.js
  src/components/Layout.jsx
  src/components/Paper/Button/ArrowButton.jsx
  src/components/Paper/Button/ArrowButton.style.js
  src/components/Paper/Button/LeftArrowButton.jsx
  src/components/Paper/Button/RightArrowButton.jsx
  src/components/Paper/Paper.jsx
  src/components/Paper/Paper.style.js
  src/components/Paper/PaperBox.jsx
  src/components/Paper/PaperBox.style.js
  src/components/Paper/PaperContainer.jsx
  src/components/Paper/Skeleton/Skeleton.jsx
  src/components/Paper/Skeleton/Skeleton.style.js
  src/components/Paper/Skeleton/SkeletonElement.jsx
  src/hooks/useFetchData.js
  src/pages/List/List.jsx
  src/router/router.jsx
  src/utils/getSortedData.js
Labels: 매운맛🔥, 기능

#48 [Feat] post page PaperInfo 컴포넌트 커스터마이징
  .github/img.png
  README.md
  src/apis/postApis.js
  src/assetes/images/add-icon.svg
  src/assetes/images/delete-icon.svg
  src/assetes/images/plus-icon.svg
  src/assetes/images/share-icon.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.style.js
  src/components/Card/CardContainer.style.js
  src/components/Card/PaperHeader.jsx
  src/components/Card/PaperHeader.style.js
  src/components/Card/RelationBadge.jsx
  src/components/PaperInfo.jsx
  src/components/PaperInfo.style.horizon.js
  src/components/PaperInfo.style.js
  src/constants/colorMapper.js
  src/pages/Post/Post.jsx
  src/pages/Post/Post.stytle.js
Labels: 매운맛🔥, 디자인, 기능

#52 [Feat] 내비게이션바 버튼 조건부 렌더링 구현 / 바디 태그 속성 레이아웃 페이지에 적용
  src/GlobalStyles.jsx
  src/components/Button/LinkButton.jsx
  src/components/Header/Header.jsx
  src/components/Home/MainBoxFirst.jsx
  src/components/Home/MainBoxSecond.jsx
  src/components/Home/MainImgBox.jsx
  src/components/Home/MainImgItemBox.jsx
  src/components/Home/MainItemBasicBox.jsx
  src/components/Home/MainItemBox.jsx
  src/components/Home/MainItemBox.style.js
  src/components/Home/MainTextBox.jsx
  src/components/Layout.jsx
  src/components/Layout.style.js
  src/pages/Home/Home.style.js
Labels: 디자인, 기능

#53 [Func] 롤링페이퍼 메세지 보내기 페이지 : SubmitButton 활성화 및 데이터 보내기
  src/apis/recipientApis.js
  src/components/Button/SubmitButton.jsx
  src/components/Button/SubmitButton.style.jsx
  src/components/Text/Editor.jsx
  src/pages/Message/SendMessage.jsx
Labels: 매운맛🔥, 기능

#55 Feat: list-post/id-create messages 페이지 연결
  src/components/Card/Card.jsx
  src/components/Card/PaperHeader.jsx
  src/components/Card/PostPageHeader.jsx
  src/components/Card/PostPageHeader.style.js
  src/components/Common/ImageList.style.js
  src/constants/colorMapper.js
  src/pages/Post/Post.jsx
Labels: 매운맛🔥, 기능

#59 [Feat] post page 카드 상태 및 삭제기능 구현
  src/apis/postApis.js
  src/assetes/images/edit-button.svg
  src/components/Card/Card.jsx
  src/components/Card/CardContainer.jsx
  src/components/Card/PostPageHeader.style.js
  src/pages/Post/Post.jsx
  src/pages/Post/Post.stytle.js
Labels: 매운맛🔥, 기능

#62 [Refactor] 정렬기능 수정 및 디자인 수정
  src/apis/fetchData.js
  src/components/Paper/Button/ArrowButton.style.js
  src/components/Paper/Paper.jsx
  src/components/Paper/Paper.style.js
  src/components/Paper/PaperBox.jsx
  src/pages/List/List.jsx
  src/utils/getSortedData.js
Labels: 디자인, 기능

#63 [Func] 롤링페이퍼 메세지 보내기 페이지 : recipientId값 받아오기 구현 및 에디터 줄바꿈 구현(모든 기능 완료)
  package-lock.json
  src/components/Button/ToggleButton.jsx
  src/components/Button/ToggleButton.style.jsx
  src/components/Input/InputText.jsx
  src/components/Input/InputText.style.jsx
  src/components/ProfileImages/ProfileImagesOptionList.jsx
  src/components/Text/Editor.jsx
  src/pages/Message/SendMessage.jsx
Labels: 매운맛🔥, 기능

#72 [Design] 롤링페이퍼 메시지 보내기 페이지 : 반응형 디자인 적용(페이지 완료)
  src/components/Button/SubmitButton.style.jsx
  src/components/Button/ToggleButton.style.jsx
  src/components/Input/InputText.jsx
  src/components/Input/InputText.style.jsx
  src/components/ProfileImages/ProfileImagesMain.style.jsx
  src/components/Text/Editor.style.jsx
  src/pages/Message/SendMessageForm.style.jsx
Labels: 매운맛🔥, 디자인

#74 [Design] 스타일 마무리&코드수정
  src/components/CreatePaper/BackgroundSelector.jsx
  src/components/CreatePaper/BackgroundText.jsx
  src/components/CreatePaper/ColorImageSelector.jsx
  src/components/CreatePaper/CreateButton.jsx
  src/components/CreatePaper/CreateButton.style.jsx
  src/components/CreatePaper/FormArea.jsx
  src/components/CreatePaper/RecipientInput.jsx
Labels: 디자인

#71 [Feat] post/id 페이지 모달 구현.
  .gitignore
  public/index.html
  src/components/Card/Card.jsx
  src/components/Card/Card.style.js
  src/components/Card/CardContainer.jsx
  src/components/CreatePaper/BackgroundBox.jsx
  src/components/CreatePaper/ColorImgSelector.jsx
  src/components/Home/MainBox.style.js
  src/components/Modal/CardModal.jsx
  src/components/Modal/CardModal.style.js
  src/components/Modal/ModalPortal.js
  src/pages/Post/Post.jsx
Labels: 매운맛🔥, 디자인, 기능

#78 [Desgin] 404 NotFound 페이지 구현
  src/assets/images/not-found.png
  src/pages/Error/Error.jsx
  src/pages/List/List.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/NotFound.style.jsx
  src/router/router.jsx
Labels: 매운맛🔥, 디자인

#84 [Feat] 이모지 리스트 전체(최대 9개) 숨기기/보이기 기능 추가
  src/components/Card/PostPageHeader.jsx
  src/components/Card/PostPageHeader.style.js
Labels: 기능

#85 [Refactor] 스타일드 분리
  src/components/CreatePaper/BackgroundBox.jsx
  src/components/CreatePaper/BackgroundSelector.jsx
  src/components/CreatePaper/BackgroundSelector.style.js
  src/components/CreatePaper/BackgroundText.jsx
  src/components/CreatePaper/BackgroundText.style.js
  src/components/CreatePaper/ColorImageSelector.jsx
  src/components/CreatePaper/FormArea.jsx
  src/components/CreatePaper/FormArea.style.js
  src/components/CreatePaper/RecipientInput.jsx
  src/components/CreatePaper/RecipientInput.style.js
  src/pages/CreatePaper/CreatePaper.jsx
  src/router/router.jsx
Labels: 디자인

#86 [Design] 롤링페이퍼 메세지 보내기 페이지 : 통일성 유지를 위한 스타일링 수정
  src/components/Button/SubmitButton.style.js
  src/components/Button/ToggleButton.style.js
  src/components/Input/InputText.style.js
  src/components/ProfileImages/ProfileImagesMain.jsx
  src/components/ProfileImages/ProfileImagesMain.style.js
  src/components/ProfileImages/ProfileImagesOptionList.style.js
  src/components/Text/Editor.style.jsx
  src/pages/Message/SendMessage.jsx
  src/pages/Message/SendMessageForm.style.js
  src/pages/NotFound/NotFound.style.js
Labels: 매운맛🔥, 디자인
